import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.container}>
          <h1 className={styles.heading_1}>Word List</h1>
          <ul>
            {props.files.map((file, index) => (
              <li key={index}><a href={`/${file.split('.')[0]}`}>{file.split('.')[0]}</a></li>
            ))}
          </ul>
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const path = require('path');
  const fs = require('fs');
  const dir = path.join(process.cwd(), '/src/data');
  const files = fs.readdirSync(dir);
  return {
    props: {
      files
    }
  }
}
